import "./styles.css";

var copyButton,
  imagePinner,
  pinnerStatus,
  pinnersBlock,
  redirectBlock,
  sendPinnerStatus,
  textPinner,
  toggleDisplayContent,
  version;

redirectBlock = document.getElementById("redirect");

pinnersBlock = document.getElementById("pinners");

textPinner = document.getElementById("textPinner");

imagePinner = document.getElementById("imagePinner");

version = document.getElementById("version");

copyButton = document.getElementById("copyButton");

pinnerStatus = {
  text: false,
  image: false,
};

textPinner.addEventListener("change", function () {
  pinnerStatus.text = this.checked;
  chrome.storage.local.set({
    pinnerStatus: pinnerStatus,
  });
  sendPinnerStatus();
});

imagePinner.addEventListener("change", function () {
  pinnerStatus.image = this.checked;
  chrome.storage.local.set({
    pinnerStatus: pinnerStatus,
  });
  sendPinnerStatus();
});

chrome.runtime.onMessageExternal.addListener(function (request) {
  if (request && request.apiKey && request.uid) {
    toggleDisplayContent({
      apiKey: request.apiKey,
      uid: request.uid,
    });
  }
});

chrome.storage.local.get().then(function (store) {
  imagePinner.checked = store.pinnerStatus
    ? store.pinnerStatus.image
    : pinnerStatus.image;
  textPinner.checked = store.pinnerStatus
    ? store.pinnerStatus.text
    : pinnerStatus.text;
  pinnerStatus = store.pinnerStatus
    ? store.pinnerStatus
    : {
        text: false,
        image: false,
      };
  sendPinnerStatus();
  toggleDisplayContent(store.clientData);
});

toggleDisplayContent = function (data) {
  if (data) {
    redirectBlock.style.display = "none";
    pinnersBlock.style.display = "flex";
  } else {
    redirectBlock.style.display = "flex";
    pinnersBlock.style.display = "none";
  }
};

sendPinnerStatus = function () {
  chrome.runtime.sendMessage({
    pinnerStatus: pinnerStatus,
  });
};

copyButton.onclick = function () {
  chrome.runtime.sendMessage("getCurrentUrl");
};

version.innerText = "Version: " + chrome.runtime.getManifest().version;

// ---
// generated by coffee-script 1.9.2
